---
################################################################################
# Routes (for terminus)                                                        #
################################################################################
# https://docs.puppetlabs.com/puppet/latest/reference/config_file_routes.html
# https://docs.puppetlabs.com/references/latest/indirection.html
# https://docs.puppetlabs.com/puppetdb/2.2/connect_puppet_master.html
# https://docs.puppetlabs.com/puppetdb/2.2/connect_puppet_apply.html

#
# Puppet Master
#
master:
  facts:
    # conf: facts_terminus
    #terminus: puppetdb
    cache: yaml
  data_binding:
    # conf: data_binding_terminus
    terminus: hiera
  node:
    # conf: node_terminus, default: plain
    terminus: exec
    # conf: node_cache_terminus
    cache: write_only_yaml
  resource:
    terminus: ral
  catalog:
    # conf: catalog_terminus
    terminus: compiler
    # conf: catalog_cache_terminus
    #cache: store_configs
  report:
    terminus: processor
  #  cache: yaml

