---
################################################################################
# Role: server                                                                 #
################################################################################

classes:
  - epel

hosts::host_entries:
  'service3':
    ip: '10.0.0.3'
    host_aliases:
      - 'srv3'

test::sub:
  duh: '123'
  oops: '567'
  yes:  'sir'
